Level Up - Semana 11
raulalvesre/vayu pull request #11
Opened 2022-04-28 18:09 UTC by raulalvesre

2022-05-04 17:03 UTC, jonilsonds9 requested changes

2022-05-04 17:03 UTC, jonilsonds9 commented on src/main/java/br/com/vayu/models/User.java
> +    private int id;
Aqui deveria ser Long

2022-05-04 17:03 UTC, jonilsonds9 commented on src/test/java/br/com/vayu/controllers/CategoryApiControllerTest.java
> +    }
Como esses dois testa o caso de sucesso poderia ser um método só

2022-05-04 17:03 UTC, jonilsonds9 commented on src/test/java/br/com/vayu/repositories/CategoryRepositoryTest.java
> +        em.clear();
Precisa mesmo desses caras?

2022-05-04 17:03 UTC, jonilsonds9 commented on src/test/java/br/com/vayu/repositories/CourseRepositoryTest.java
> +        ;
Sobrou?

2022-05-04 17:03 UTC, jonilsonds9 commented on src/test/java/br/com/vayu/repositories/CourseRepositoryTest.java
> +        ;
??

2022-05-04 17:03 UTC, jonilsonds9 commented on src/test/java/br/com/vayu/repositories/CourseRepositoryTest.java
> +        em.clear();
Cara, é estranho fazer isso, principalmente porque não tem relacionamentos nos objetos

2022-05-04 17:03 UTC, jonilsonds9 commented on src/test/java/br/com/vayu/repositories/SubcategoryRepositoryTest.java
> +        em.clear();
Usando o repository acho que não precisa tá chamando isso, só deixa o teste verboso

2022-05-04 17:03 UTC, jonilsonds9 commented on system.properties
> +java.runtime.version=17
Porque precisou desse cara?

2022-05-04 18:55 UTC, raulalvesre commented on system.properties
> +java.runtime.version=17
"Para especificar a versão do Java, siga as [seguintes instruções](https://devcenter.heroku.com/articles/java-support#specifying-a-java-version) do Heroku, criando um arquivo `system.properties` na raiz do projeto com o conteúdo `java.runtime.version=16`."

2022-05-04 18:59 UTC, raulalvesre commented on system.properties
> +java.runtime.version=17
Coloca ele no .gitignore?

2022-05-04 19:00 UTC, jonilsonds9 commented on system.properties
> +java.runtime.version=17
não, pode manter! Saquei a ideia!

2022-05-04 19:45 UTC, raulalvesre commented on src/test/java/br/com/vayu/repositories/SubcategoryRepositoryTest.java
> +        em.clear();
Corrigido.

2022-05-04 19:45 UTC, raulalvesre commented on src/test/java/br/com/vayu/repositories/CourseRepositoryTest.java
> +        em.clear();
Corrigido.

2022-05-04 19:45 UTC, raulalvesre commented on src/test/java/br/com/vayu/repositories/CourseRepositoryTest.java
> +        ;
Corrigido.

2022-05-04 19:45 UTC, raulalvesre commented on src/test/java/br/com/vayu/repositories/CourseRepositoryTest.java
> +        ;
Corrigido.

2022-05-04 19:45 UTC, raulalvesre commented on src/test/java/br/com/vayu/repositories/CategoryRepositoryTest.java
> +        em.clear();
Corrigido.

2022-05-04 19:45 UTC, raulalvesre commented on src/test/java/br/com/vayu/controllers/CategoryApiControllerTest.java
> +    }
Corrigido.

2022-05-04 19:47 UTC, jonilsonds9 approved these changes

2022-05-05 18:55 UTC, fabiuhp approved these changes

2022-05-11 16:58 UTC, merged