Level Up - Semana 12
raulalvesre/vayu pull request #12
Opened 2022-05-11 16:58 UTC by raulalvesre

2022-05-11 17:14 UTC, jonilsonds9 requested changes
Cara, vê se tem como colocar um fundo branco no diagrama, só pra facilitar a visualização!

2022-05-11 17:14 UTC, jonilsonds9 commented on src/main/java/br/com/vayu/controllers/AuthController.java
> +@RequiredArgsConstructor
Boa!

2022-05-11 17:14 UTC, jonilsonds9 commented on src/main/webapp/views/category/categoryList.jsp
> +    </footer>
Acho que essa parte deveria estar dentro de uma tag, talvez um nome como `admin-template-footer`, e ai você deixar toda a parte do restante do HTML: 
```
<footer>
    <script src="/webjars/jquery/3.1.1/jquery.min.js"></script>
    <jsp:doBody/>
</footer>
</body>
</html>
```
Ai nesse caso aqui, você não teria esse `admin-template`, do jeito que está, ficaria assim:
```
<%@tag language="java" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<%@attribute name="title" %>
<%@attribute name="cssPath" %>

<!DOCTYPE html>
<html>
<head>
    <title>${title}</title>
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'/>
    <link href="${pageContext.request.contextPath}/${cssPath}" rel="stylesheet"/>
    <link rel='stylesheet' href='/webjars/bootstrap/3.3.7/css/bootstrap.min.css'>
</head>
<body>
    <jsp:doBody/>
```
E nessas suas JSP, você teria algo como:
```
<templates:admin-template/>
colocar todo o conteúdo aqui
<admin-template-footer>
    <script src="/js/categoryList.js"/>
</admin-template-footer>
```
E se não precisar de nenhum `javascript` adicional:
```
<templates:admin-template/>
colocar todo o conteúdo aqui
<admin-template-footer/>
```

2022-05-11 17:50 UTC, raulalvesre commented on src/main/webapp/views/category/categoryList.jsp
> +    </footer>
Refatorado!

2022-05-11 18:15 UTC, jonilsonds9 approved these changes

2022-05-11 18:15 UTC, jonilsonds9 commented on src/main/webapp/views/category/categoryForm.jsp
> +</templates:admin-footer>
Aqui, como você não precisar passar nada, então poderia usar apenas assim:
```
<templates:admin-footer/>
```

2022-05-11 18:28 UTC, raulalvesre commented on src/main/webapp/views/category/categoryForm.jsp
> +</templates:admin-footer>
Refatorado no https://github.com/raulalvesre/vayu/pull/12/commits/a8ed7462ec9e6cd4257f113e60a7d35728f8e181.

2022-05-13 15:25 UTC, fabiuhp approved these changes

2022-05-20 19:57 UTC, merged