Level Up - Semana 3
raulalvesre/vayu pull request #3
Opened 2022-02-25 19:35 UTC by raulalvesre

2022-03-02 16:05 UTC, jonilsonds9 requested changes

2022-03-02 16:05 UTC, jonilsonds9 commented on src/main/java/br/com/vayu/helpers/CategoryHelper.java
> +    public static void printActiveCategories(Collection<Category> categories) {
Só achei estranho receber uma `Collection`, os cards falam que os metodos recebem um List, acho precisa ser List pra atender o card, saquei a ideia em receber algo mais geral, mas como os cards falam especificamente em List, acho que deve receber List.

2022-03-02 16:21 UTC, raulalvesre commented on src/main/java/br/com/vayu/helpers/CategoryHelper.java
> +    public static void printActiveCategories(Collection<Category> categories) {
Feito.

2022-03-02 16:28 UTC, jonilsonds9 approved these changes

2022-03-03 12:25 UTC, fabiuhp approved these changes

2022-03-03 12:26 UTC, merged